import assert from "node:assert/strict";
import vm from "node:vm";
import { createFeatureTest, read } from "../helpers/feature-test-harness.mjs";
const test = createFeatureTest("bonsai-catalog-objects");
const context = vm.createContext({ window: {} });
for (const file of ["bonsai-renderer.js", "bonsai-catalog.js", "bonsai-renderer-voxel.js"]) vm.runInContext(read(`app/features/${file}`), context);
const { AISystem6BonsaiRenderer: math, AISystem6BonsaiCatalog: catalog, AISystem6BonsaiVoxelRenderer: voxel } = context.window;
const source = JSON.parse(read("assets/bonsai/atlas-source.json"));
const world = () => ({ size: 12, catalogId: new Uint8Array(144), alt: new Uint8Array(144), tick: 500, timeOfDay: .5 });
const fill = (s,x,y,side,id) => { for(let dy=0;dy<side;dy++)for(let dx=0;dx<side;dx++)s.catalogId[(y+dy)*s.size+x+dx]=id; };
let s=world(); fill(s,1,1,3,0xd7);
let objects=math.collectCatalogObjects(s,catalog);
assert.equal(objects.length,1); assert.equal(objects[0].footprint.w,3); assert.equal(objects[0].fragment,false);
fill(s,4,1,3,0xd7); objects=math.collectCatalogObjects(s,catalog);
assert.equal(objects.length,2); assert.deepEqual(Array.from(objects,o=>o.x),[1,4]);
s.catalogId[2*12+2]=0; objects=math.collectCatalogObjects(s,catalog);
assert.equal(objects.filter(o=>!o.fragment).length,1); assert.equal(objects.filter(o=>o.fragment).length,8);
assert.ok(objects.filter(o=>o.fragment).every(o=>o.label==="infrastructure"&&o.footprint.w===1));
s=world();fill(s,1,1,3,0xd7);s.alt[2*12+2]=1;
assert.equal(math.collectCatalogObjects(s,catalog).filter(o=>!o.fragment).length,0);
s=world();fill(s,1,1,3,0xd7);const before=JSON.stringify(s);
const scene=voxel.pure.collectSceneObjects(s,voxel.pure.buildRecipes(source));
assert.equal(JSON.stringify(scene.catalogTiles),JSON.stringify(math.collectCatalogObjects(s,catalog)));
assert.equal(JSON.stringify(s),before,"collector never mutates the snapshot");
s=world();s.catalogId[13]=0xc8;
let wind=math.collectCatalogObjects(s,catalog);
assert.equal(wind[0].spriteId,"facility.wind");
let windScene=voxel.pure.collectSceneObjects(s,voxel.pure.buildRecipes(source));
assert.equal(windScene.facilities.length,1);assert.equal(windScene.catalogTiles.length,0);
s.facilityAt=new Int16Array(144).fill(-1);s.facilityAt[13]=0;
assert.equal(math.collectCatalogObjects(s,catalog).length,0,"existing codec-converted facility suppresses catalog duplicate");
const geometry = (blocks) => JSON.stringify(blocks.map(({x,y,z,sx,sy,sz,shape})=>({x,y,z,sx,sy,sz,shape})),(_,v)=>typeof v==="number"?Math.round(v*1e9)/1e9:v);
for (const entry of source.catalogSpecials) {
  const frame = { ...entry, category:"catalog", state:"normal" };
  const blocks=voxel.pure.createAssetBlocks(frame,source);
  assert.ok(blocks.length>2,`${entry.id} has articulated geometry`);
  assert.ok(blocks.every(b=>b.y-b.sy/2>=-1e-8),`${entry.id} has no underground model pieces`);
  assert.equal(geometry(blocks),geometry(voxel.pure.createAssetBlocks({...frame,state:"night",id:entry.id+".night"},source)),`${entry.id} keeps its geometry at night`);
  const fw=entry.footprint[0],fd=entry.footprint[1];
  assert.ok(blocks.every(b=>Math.abs(b.x)+b.sx/2<=fw/2+.001&&Math.abs(b.z)+b.sz/2<=fd/2+.001),`${entry.id} remains inside declared footprint`);
}
const liveWorld=world();fill(liveWorld,1,1,3,0xd7);
const liveScene=voxel.pure.collectSceneObjects(liveWorld,voxel.pure.buildRecipes(source));
const placed=voxel.pure.collectChunkBlocks(liveWorld,voxel.pure.buildRecipes(source),0,0,liveScene,true).opaque.map(b=>({...b,x:b.x-2.5,z:b.z-2.5}));
const stadium=voxel.pure.createAssetBlocks({...source.catalogSpecials.find(e=>e.id==='catalog.stadium'),category:'catalog',state:'normal'},source);
assert.equal(geometry(placed),geometry(stadium),"catalog atlas and live grouped facility use identical dimensions and geometry");
assert.ok(!stadium.some(b=>b.y-b.sy/2>.06&&Math.abs(b.x)<.01&&Math.abs(b.z)<.01&&b.sx>1&&b.sz>1),"stadium has no solid block over the playing field");
test.assert(true,"complete adjacent buildings group once; holes and unequal altitude remain one-tile fragments; every catalog landmark keeps a grounded, stable day/night footprint");
test.finish();
