// Every source file under apps/desktop/app/ must be reachable.
//
// The trap this closes: a file that is in NEITHER `appModulePaths` NOR
// `lazyRuntimePaths` is invisible to every existing gate. `lazy-module-reachable`
// only iterates the lazy list, so it cannot see a file that is in no list at all.
// `verify:floppy` only measures what the bundle contains. And a feature contract
// stays green over such a file, because the contracts `vm.runInContext` the
// source directly rather than the shipped bundle.
//
// That combination shipped `app/core/clio-project.js`: 277 lines with a passing
// 30-assertion contract, and zero bytes of it in app.bundle.js. The product had
// no ClioProject at all while the board said otherwise.
//
// So this gate does not ask "is it lazy or eager" — it asks "does anything name
// it". A file reached some other way (a Worker URL, a tooling script) is fine,
// but it has to be declared here with the reason, so an orphan is always a
// stated choice instead of an accident.

import { globSync } from "node:fs";
import { coreFiles, appModulePaths, lazyRuntimePaths, appRuntimePaths } from "../../tooling/runtime-manifest.mjs";
import { createFeatureTest, read } from "../helpers/feature-test-harness.mjs";

const test = createFeatureTest("orphan-sources");

// Files that ship no bytes through a manifest, each with the reason it is
// reachable anyway. Adding a row here is a decision; leaving one out is a bug.
const DECLARED_UNBUNDLED = {
  "app/features/bonsai-save-worker.js":
    "Web Worker entry point. bonsai-save-worker-manager.js builds its URL in a template literal, so no static list can name it and it must not enter the bundle.",
  "app/data/iphone-17e-demo-corpus.js":
    "Evaluation fixture read only by tooling/eval-mingming-outline.mjs and its feature test. Never loaded by the app; it sits under app/data/ for historical reasons.",
  "app/generated/bonsai-textures.js":
    "Texture-atlas runtime manifest from the in-flight ART lane: generated by tooling/build-bonsai-texture-atlas.mjs and asserted by tests/features/bonsai-textures.test.mjs; the renderers will name it when the texture lane lands, so it must not enter the bundle today.",
  "app/core/endfield-grounding.js":
    "Endfield grounding core, loaded lazily through ensureLazySystemModule(\"app/core/endfield-grounding.js\", ...) from app/core/actions.js and app/core/chat-messages.js. It is not named by a createLazyModuleLoader in config.js or an index.html script tag, so the static manifest cannot list it; the runtime loader string is the only reachable path and must not be bundled.",
  "app/content/shared-disks-panel.js":
    "The window and its list for the demonstration project disks. tooling/build-shared-project-disks.mjs appends this file to app/content/shared-project-disks.js, so the panel ships inside the generated disk module the launch links already fetch — reachable without a manifest row, and deliberately not in the boot bundle (it would spend floppy bytes on a window most boots never open).",
  "app/features/bonsai-sc2000-reader.js":
    "SC2000.DAT container reader, clean-room and tested (tests/features/bonsai-sc2000-reader.test.mjs). The loader that named it had no caller anywhere in the tree, so the loader is gone and the file is declared unbundled: the lane is unwired, not lazy. Wiring it is one createLazyModuleLoader the day the Bonsai import lane starts reading containers.",
  "app/features/bonsai-large-dat-reader.js":
    "LARGE.DAT sprite reader, clean-room and tested. Same story as the SC2000 container reader beside it: its loader named it and nothing called the loader, so the file is declared unbundled rather than shipped behind a loader nobody reaches.",
  "app/features/bonsai-sc2k-palette.js":
    "PAL_MSTR.BMP palette reader, clean-room and tested: it turns the large-dat reader's output into pixel buffers. Unwired with its two siblings, declared here for the same reason.",
  "app/core/persistence-scan-shadow.js":
    "The save-plan shadow comparison: a development instrument whose guard in app/core/persistence-status.js reads window.AISystem6ScanShadow only to find the module absent, and whose e2e probe (tests/e2e/scan-shadow.spec.mjs) no longer exists. Its loader is gone rather than shipping an instrument nothing loads.",
};

const listed = new Set(
  [...coreFiles, ...appModulePaths, ...lazyRuntimePaths, ...appRuntimePaths].map((p) => p.split("?")[0])
);

// A loader may also name a file by string literal; those count as reachable.
const loaderText = read("app/core/config.js") + read("index.html");
for (const match of loaderText.matchAll(/["'](app\/[\w./-]+\.js)(\?[^"']*)?["']/g)) listed.add(match[1]);

const sources = globSync("apps/desktop/app/**/*.js")
  .map((p) => p.replace("apps/desktop/", ""))
  .filter((p) => !p.startsWith("app/vendor/"))
  .sort();

test.assert(sources.length > 100, `the scan found the app tree (${sources.length} files)`);

const orphans = sources.filter((p) => !listed.has(p) && !DECLARED_UNBUNDLED[p]);
test.assert(
  orphans.length === 0,
  orphans.length === 0
    ? "every source file is named by a manifest, a loader, or the declared-unbundled list"
    : `unreachable source file(s) with no declared reason: ${orphans.join(", ")}`
);

// The declared list must stay honest in both directions: a file that has since
// been wired into a manifest should lose its row here rather than accumulate.
for (const [path, reason] of Object.entries(DECLARED_UNBUNDLED)) {
  test.assert(sources.includes(path), `declared-unbundled ${path} still exists`);
  test.assert(reason.length > 40, `declared-unbundled ${path} states a real reason`);
  test.assert(
    !listed.has(path),
    `declared-unbundled ${path} is still genuinely unnamed (remove its row once a manifest names it)`
  );
}

test.finish();
