#!/usr/bin/env python3
"""build_guide.py: renders build/guide.wav, the source that ACE-Step 1.5 covers.

    python3 -I music/build_guide.py              # render + measure (Whisper, pitch, loudness; ~6 min)
    python3 -I music/build_guide.py --no-qa      # render only (~2 min with warm caches)
    python3 -I music/build_guide.py --workers 4

The final song is regenerated by ACE-Step 1.5 in cover mode (music/ace_cover.py), which keeps the
source's structure and tempo and re-sings it with a realistic voice.  This is that source: the new
Kokoro singer (music/sing_world.py, af_heart) clear and in tune on top of a warm, simple band that
follows the score's chords and sections and plays its drums on the exact EVENTS times of data/data.js.
Nothing here changes a timing: every note comes from score.json, every drum hit from data.js.

Writes (48 kHz, 24-bit, stereo, exactly DUR long):
  build/guide.wav               the mix: -14 LUFS integrated, true peak <= -1 dBTP
  build/guide_vocals.wav        the vocal bus (with its reverb) through the master's gain
  build/guide_instrumental.wav  the band through the same gain (vocals + instrumental = guide)
  build/guide_stems/*.wav       pre-master tracks: lead chant choir spoken chops drums bass keys strings mallets
  build/guide-qa.json           the measurements (music/guide_qa.py)
The old engine (build_song.py -> build/song.wav) is untouched.  See music/PRODUCTION.md, "Guide for
ACE-Step cover".
"""
import argparse
import hashlib
import json
import math
import os
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.dont_write_bytecode = True

import numpy as np            # noqa: E402
import soundfile as sf        # noqa: E402

import qa                     # noqa: E402
import sing_world as SW       # noqa: E402
from dsp import (SR, compressor, convolve, db, deesser, eq, hp, limiter, lp, lufs, n_of, plate_ir,  # noqa: E402
                 pocket, room_ir, stereo, true_peak, undb, width)
from synth import SF2, write_midi   # noqa: E402

ROOT = os.path.dirname(HERE)
BUILD = os.path.join(ROOT, "build")
FLUID = os.path.join(ROOT, ".cache", "fluid")

# GM programs (FluidR3_GM)
EP, PIANO, STRINGS, PAD, GLOCK, CELESTA, ORGAN, BASS = 4, 0, 48, 89, 9, 8, 16, 33
# GM drum notes (channel 10, Standard kit)
DRUM = {"kick": 36, "snare": 38, "ghost": 38, "clap": 39, "hat": 42, "openHat": 46, "crash": 49,
        "chokedCrash": 55, "tambourine": 54, "tom": 41, "snap": 37, "keystroke": 37}
# band cuts (beats): stop-times, the stumble, breakdown bar 1, the silent pen (parts.bass.cuts)
TARGET_LUFS = -14.0
CEILING = -1.2              # limiter ceiling, dBTP (the brief: <= -1)
VOX_OVER_BED = 3.5          # dB, 1-5 kHz, on sung frames


def log(msg, t0=[time.time()]):
    print("[%6.1fs] %s" % (time.time() - t0[0], msg), flush=True)


# ------------------------------------------------------------------------------------------------
# FluidSynth (any channel), cached, latency-compensated
# ------------------------------------------------------------------------------------------------
def _fluid_render(notes_beats, program, channel, wav, cc=None, gain=0.5):
    mid = wav[:-4] + ".mid"
    write_midi(mid, notes_beats, program, channel=channel, cc=cc)
    subprocess.run(["fluidsynth", "-ni", "-q", "-R", "0", "-C", "0", "-g", str(gain), "-r", str(SR),
                    "-o", "synth.polyphony=256", "-T", "wav", "-O", "float", "-F", wav, SF2, mid],
                   check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    os.remove(mid)


def latency(program, channel, note):
    """Onset latency (s) of a GM program / drum note: one calibration note, measured at 10 % of peak."""
    os.makedirs(FLUID, exist_ok=True)
    wav = os.path.join(FLUID, "gcal_%d_%d_%d.wav" % (program, channel, note))
    if not os.path.exists(wav):
        _fluid_render([(note, 1.0, 1.0, 100)], program, channel, wav)
    y, _ = sf.read(wav, dtype="float64", always_2d=True)
    m = np.abs(y).max(axis=1)
    i0 = int(0.5 * SR)
    seg = m[i0 - 200:i0 + 6000]
    k = int(np.argmax(seg > 0.1 * seg.max()))
    return max(0.0, (k - 200) / SR)


def gm(notes, program, total_s, channel=0, cc=None, tag="gm", cal_note=60):
    """notes: [(midi, start s, dur s, velocity)]; cc: [(t s, controller, value)] -> stereo, total_s long."""
    nb = [(int(m), round(t * 2, 6), round(max(d, 0.02) * 2, 6), int(v)) for m, t, d, v in notes]
    cb = [(round(t * 2, 6), int(c), int(v)) for t, c, v in (cc or [])]
    key = hashlib.sha1(json.dumps([nb, program, channel, cb, round(total_s, 3), "g2"]).encode()).hexdigest()[:20]
    os.makedirs(FLUID, exist_ok=True)
    wav = os.path.join(FLUID, "guide_%s_%s.wav" % (tag, key))
    if not os.path.exists(wav):
        _fluid_render(nb, program, channel, wav, cb)
    y, sr = sf.read(wav, dtype="float64", always_2d=True)
    assert sr == SR
    sh = int(round(max(0.0, latency(program, channel, cal_note) - 0.0008) * SR))
    y = y[sh:]
    out = np.zeros((n_of(total_s), 2))
    k = min(len(out), len(y))
    out[:k] = y[:k]
    return out


# ------------------------------------------------------------------------------------------------
# the band, from score.json (chords, sections, parts) and data.js (EVENTS)
# ------------------------------------------------------------------------------------------------
class Band:
    def __init__(self, S, events, dur):
        self.S, self.E, self.dur = S, events, dur
        self.spb = 60.0 / S["bpm"]
        self.sections = sorted(S["sections"], key=lambda s: s["startBeat"])
        self.chords = sorted(S["chords"], key=lambda c: c["startBeat"])
        self.cuts = [(a, a + b) for a, b, _ in S["parts"]["bass"]["cuts"] if a < 296]   # outro bar 3 is arranged below
        self.sil = [(a * self.spb, (a + b) * self.spb) for a, b, _ in S["parts"]["silence"]]

    def section(self, beat):
        cur = self.sections[0]["name"]
        for s in self.sections:
            if beat >= s["startBeat"] - 1e-9:
                cur = s["name"]
        return cur

    def cut(self, notes):
        """drop / shorten notes (beats) that sound inside a cut window"""
        out = []
        for m, b, d, v in notes:
            e = b + d
            for a, z in self.cuts:
                if a <= b < z:
                    d = 0
                    break
                if b < a < e:
                    e = a
                    d = e - b
            if d > 0.05:
                out.append((m, b, d, v))
        return out

    def sec_notes(self, notes):
        return [(m, b * self.spb, d * self.spb, v) for m, b, d, v in notes]

    # ---- keys
    def keys(self):
        ep, piano, strings, pad = [], [], [], []
        for c in self.chords:
            b0, L, sym = c["startBeat"], c["beats"], c["symbol"]
            sec = self.section(b0)
            v = c["notes"][1:]
            if sec == "boot" or b0 >= 300:                          # the boot chord and the end chord
                ep += [(m, b0, L - 0.05, 52) for m in v]
                strings += [(m, b0, L - 0.05, 70) for m in v]
                pad += [(m, b0, L - 0.05, 58) for m in v[:4]]
            elif sec in ("intro", "verse1", "verse2", "post1", "post2") or (sec == "outro" and b0 < 296):
                pat = [(0, 1.4, 60), (1.5, 0.45, 48), (2.5, 1.4, 54)] if L >= 4 else [(0, 1.4, 60), (1.5, 0.45, 48)]
                ep += [(m, b0 + o, d, vel) for o, d, vel in pat for m in v]
            elif sec in ("pre1", "pre2"):
                ep += [(m, b0, L - 0.05, 54) for m in v]
                strings += [(m, b0, L - 0.02, 76) for m in v]
            elif sec in ("chorus1", "chorus2", "chorus3"):
                ep += [(m, b0, L - 0.05, 46) for m in v]
                for k in range(int(L)):
                    piano += [(m + 12, b0 + k + 0.5, 0.32, 64 if k % 2 == 0 else 56) for m in v]
                strings += [(m, b0, L - 0.02, 72) for m in v]
                pad += [(m, b0, L - 0.02, 50) for m in v[:4]]
            elif sec == "bridge":
                if b0 >= 232:
                    ep += [(m, b0, L - 0.05, 54) for m in v]
                    pad += [(m, b0, L - 0.02, 56) for m in v]
                    strings += [(m, b0, L - 0.02, 64) for m in v]
            elif sec == "breakdown":
                if 244 <= b0 < 252:
                    piano += [(m, b0, L - 0.1, 46) for m in v]
                elif b0 >= 252:
                    strings += [(m, b0, L - 0.02, 66) for m in v]
                    pad += [(m, b0, L - 0.02, 54) for m in v]
            elif sec == "outro" and 296 <= b0 < 300:
                piano += [(m, b0, L - 0.05, 56) for m in v]
                ep += [(m, b0, L - 0.05, 40) for m in v]
        # the bridge comp: EP stabs on the big-beat kick rhythm (keys.bridgeComp)
        for st in self.S["parts"]["keys"].get("bridgeComp", []):
            ep += [(m, st["startBeat"], 0.4, 70) for m in st["notes"]]
        # the stabs (the HAND hits, the chorus hits, the era changes): piano + EP, not brass
        for st in self.S["parts"]["stabs"]["brass"]:
            piano += [(m, st["startBeat"], 0.45, 90) for m in st["notes"]] + [(m + 12, st["startBeat"], 0.45, 80) for m in st["notes"]]
        # pre-chorus strings swell (CC11 across the section, as the old riser did)
        cc = []
        for s in self.sections:
            if s["name"] in ("pre1", "pre2"):
                a, z = s["startBeat"], s["startBeat"] + 13.5
                for k in range(28):
                    cc.append((a + (z - a) * k / 27, 11, int(45 + 75 * k / 27)))
                cc.append((s["startBeat"] + s["beats"], 11, 100))
            elif s["name"] in ("boot",):
                for k in range(9):
                    cc.append((k * 0.5, 11, int(60 + 50 * k / 8)))
                cc.append((8, 11, 100))
        cc.sort()
        T = self.dur
        parts = {
            "ep": gm(self.sec_notes(self.cut(ep)), EP, T, tag="ep"),
            "piano": gm(self.sec_notes(self.cut(piano)), PIANO, T, tag="piano"),
            "strings": gm(self.sec_notes(self.cut(strings)), STRINGS, T, cc=[(b * self.spb, c, v) for b, c, v in cc], tag="strings"),
            "pad": gm(self.sec_notes(self.cut(pad)), PAD, T, tag="pad"),
        }
        return parts

    # ---- bass: the two floppy drives' notes, on a warm fingered bass
    def bass(self):
        notes = []
        for name, vel in (("floppyA", 96), ("floppyB", 72)):
            for t, m, d in self.E[name]:
                m = int(m)
                while m < 31:
                    m += 12
                while m > 55:
                    m -= 12
                notes.append((m, t, max(0.09, d * 0.9), vel))
        notes = self._sil_cut(notes)
        return gm(notes, BASS, self.dur, tag="bass", cal_note=40)

    def _sil_cut(self, notes):
        out = []
        for m, t, d, v in notes:
            for a, z in self.sil:
                if a <= t < z:
                    d = 0
                elif t < a < t + d:
                    d = a - t
            if d > 0.02:
                out.append((m, t, d, v))
        return out

    # ---- melodic accents: glockenspiel bells, the bridge years on celesta, the riff on a soft organ
    def mallets(self):
        bells = [(int(m), t, 0.6, 92) for t, m in self.E["bell"]]
        beeps = [(int(m), t, 0.45, 74) for t, m in self.E["beep"]]
        riff = [(int(m), t, max(0.08, d * 0.92), 70) for t, m, d in self.E["riff"]]
        return {"glock": gm(bells, GLOCK, self.dur, tag="glock", cal_note=84),
                "celesta": gm(beeps, CELESTA, self.dur, tag="celesta", cal_note=72),
                "organ": gm(self._sil_cut(riff), ORGAN, self.dur, tag="organ", cal_note=67)}

    # ---- drums: a natural GM kit on the EVENTS times
    def drums(self):
        E, T = self.E, self.dur
        beat = lambda t: t / self.spb

        def vel_kick(t):
            b = beat(t)
            return 112 if abs(b / 4 - round(b / 4)) < 1e-6 else (104 if abs(b - round(b)) < 1e-6 else 92)

        def vel_hat(t):
            b = beat(t)
            f = b - math.floor(b + 1e-9)
            base = 70 if f < 1e-6 else (58 if abs(f - 0.5) < 1e-6 else 46)
            return base + (int(round(b * 4)) * 7919 % 9) - 4

        builds = [(28.0, 34.75), (76.0, 82.75)]

        def vel_snare(t):
            for a, z in builds:
                if a <= t < z and (t - a) > 4.0:
                    return int(64 + 44 * (t - a) / (z - a))
            return 100

        tracks = {}
        spec = {
            "kick": [(DRUM["kick"], t, 0.2, vel_kick(t)) for t in E["kick"]],
            "snare": [(DRUM["snare"], t, 0.2, vel_snare(t)) for t in E["snare"]] +
                     [(DRUM["ghost"], t, 0.1, 34) for t in E["ghost"]],
            "clap": [(DRUM["clap"], t, 0.2, 88) for t in E["clap"]] + [(DRUM["snap"], t, 0.1, 64) for t in E["snap"]],
            "hats": [(DRUM["hat"], t, 0.1, vel_hat(t)) for t in E["hat"] if t not in set(E["openHat"])] +
                    [(DRUM["openHat"], t, 0.25, 66) for t in E["openHat"]],
            "cymbals": [(DRUM["crash"], t, 1.0, 96) for t in E["crash"]] + [(DRUM["chokedCrash"], t, 0.3, 88) for t in E["chokedCrash"]],
            "perc": [(DRUM["tambourine"], t, 0.1, 40 + (8 if abs(beat(t) * 2 - round(beat(t) * 2)) < 1e-6 else 0)) for t in E["tambourine"]] +
                    [(DRUM["tom"], t, 0.3, 84) for t in E["tom"]],
            "keystroke": [(DRUM["keystroke"], t, 0.1, 46) for t in E["keystroke"][:1]],
        }
        for name, notes in spec.items():
            cal = notes[0][0] if notes else 38
            tracks[name] = gm(notes, 0, T, channel=9, tag="dr_" + name, cal_note=cal)
        return tracks


# ------------------------------------------------------------------------------------------------
# mix
# ------------------------------------------------------------------------------------------------
def rms_db(x):
    return float(db(np.sqrt(np.mean(np.asarray(x, dtype=float) ** 2) + 1e-20)))


def norm_to(x, target_db, active=True):
    """Gain a track so that its active RMS (frames within 30 dB of its peak frame) is target_db."""
    m = stereo(x).mean(axis=1)
    fr = m[: len(m) // 2400 * 2400].reshape(-1, 2400)
    e = np.sqrt(np.mean(fr ** 2, axis=1) + 1e-20)
    if not np.any(e > 0):
        return x, 0.0
    a = e[e > e.max() * 10 ** (-30 / 20)] if active else e
    g = target_db - float(db(np.sqrt(np.mean(a ** 2))))
    return x * undb(g), g


def section_gain(S, dur, gains_db, ramp=0.03):
    """A smooth per-section gain curve (linear) from {section: dB}."""
    spb = 60.0 / S["bpm"]
    n = n_of(dur)
    g = np.zeros(n)
    for s in S["sections"]:
        a, b = n_of(s["startBeat"] * spb), min(n, n_of((s["startBeat"] + s["beats"]) * spb))
        g[a:b] = gains_db.get(s["name"], 0.0)
    k = max(1, n_of(ramp))
    g = np.convolve(np.pad(g, (k // 2, k - k // 2 - 1), mode="edge"), np.ones(k) / k, mode="valid")
    return undb(g)


def band_ratio(vox, bed, lo=1000.0, hi=5000.0, win=0.05, rel=15.0):
    """Vocal-over-bed level (dB) in lo..hi on sung frames: mean powers over frames where the vocal band
    is within `rel` dB of its 95th percentile."""
    from dsp import bp
    v = bp(stereo(vox).mean(axis=1), lo, hi, 4)
    b = bp(stereo(bed).mean(axis=1), lo, hi, 4)
    W = n_of(win)
    k = len(v) // W
    pv = np.mean(v[:k * W].reshape(k, W) ** 2, axis=1)
    pb = np.mean(b[:k * W].reshape(k, W) ** 2, axis=1)
    if not np.any(pv > 0):
        return None, 0
    ref = np.percentile(10 * np.log10(pv[pv > 0] + 1e-20), 95)
    m = 10 * np.log10(pv + 1e-20) > ref - rel
    if m.sum() < 3:
        return None, int(m.sum())
    return float(10 * np.log10(pv[m].mean() / (pb[m].mean() + 1e-20))), int(m.sum())


def tame(x, crest_db):
    """Hold a bus's peaks to crest_db over its active RMS (a transparent brick-wall on the GM kit's and
    the stab chords' transients, so the master limiter does not have to)."""
    m = stereo(x).mean(axis=1)
    fr = m[: len(m) // 2400 * 2400].reshape(-1, 2400)
    e = np.sqrt(np.mean(fr ** 2, axis=1) + 1e-20)
    a = e[e > e.max() * 10 ** (-30 / 20)]
    ref = float(db(np.sqrt(np.mean(a ** 2))))
    y, _ = limiter(x, ceiling_db=ref + crest_db, lookahead=0.003, release=0.05, k=2)
    return y


def vocal_chain(x, kind):
    x = stereo(x)
    if kind == "lead":
        x = eq(x, ("hp", 90, 0.7), ("hp", 90, 0.7), ("peak", 260, 1.0, -2.5), ("peak", 3200, 0.9, 2.5), ("highshelf", 9000, 0.7, 2.0))
        x = deesser(x, 6500, thr=-34, ratio=4, max_cut=6)
        x = compressor(x, thr=-24, ratio=3.0, attack=0.005, release=0.09, makeup=6.0)
    elif kind == "chant":
        x = eq(x, ("hp", 100, 0.7), ("hp", 100, 0.7), ("peak", 250, 1.0, -2.0), ("peak", 3000, 0.9, 2.0), ("highshelf", 9000, 0.7, 1.5))
        x = deesser(x, 6000, thr=-34, ratio=4, max_cut=6)
        x = compressor(x, thr=-24, ratio=3.0, attack=0.005, release=0.09, makeup=6.0)
    elif kind == "choir":
        x = eq(x, ("hp", 140, 0.7), ("hp", 140, 0.7), ("peak", 300, 1.0, -3.0), ("peak", 4000, 0.9, 1.0), ("highshelf", 10000, 0.7, 1.5))
        x = deesser(x, 6500, thr=-34, ratio=4, max_cut=6)
        x = compressor(x, thr=-22, ratio=2.5, attack=0.008, release=0.12, makeup=4.0)
        x = width(x, 1.15)
    elif kind == "spoken":
        x = eq(x, ("hp", 100, 0.7), ("peak", 250, 1.0, -2.0), ("peak", 3000, 0.9, 2.0))
        x = compressor(x, thr=-24, ratio=2.5, attack=0.005, release=0.1, makeup=4.0)
    elif kind == "chops":
        x = eq(x, ("hp", 200, 0.7), ("peak", 3000, 0.9, 1.5))
    return x


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--no-qa", action="store_true")
    ap.add_argument("--no-whisper", action="store_true")
    ap.add_argument("--workers", type=int, default=4)
    args = ap.parse_args()

    with open(os.path.join(HERE, "score.json")) as f:
        S = json.load(f)
    DUR, EVENTS = qa.read_data_js(os.path.join(ROOT, "data", "data.js"))
    spb = 60.0 / S["bpm"]
    assert abs(S["durationBeats"] * spb - DUR) < 1e-9, "score.json and data.js disagree on the length"
    N = n_of(DUR)
    log("score: %s, %d bpm, %.1f s, %d lines" % (S["title"], S["bpm"], DUR, len(S["lines"])))

    # ---- voices
    V, metas = SW.render(S, DUR, workers=args.workers)
    log("voices: %s" % ", ".join("%s %.1f dB" % (k, rms_db(v)) for k, v in sorted(V.items())))

    # ---- band
    band = Band(S, EVENTS, DUR)
    dr = band.drums()
    K = band.keys()
    B = band.bass()
    M = band.mallets()
    log("band rendered (FluidSynth)")

    # drums bus
    dgain = {"kick": 0.0, "snare": -2.0, "clap": -5.0, "hats": -11.0, "cymbals": -10.0, "perc": -14.0, "keystroke": -6.0}
    drums = np.zeros((N, 2))
    for k, x in dr.items():
        if k == "keystroke":
            continue
        drums += x * undb(dgain[k])
    room = room_ir(0.45, seed=5)
    drums += convolve(dr["snare"] * undb(dgain["snare"]) + dr["clap"] * undb(dgain["clap"]), room) * undb(-17)
    drums = eq(drums, ("hp", 30, 0.7), ("peak", 400, 1.0, -1.5), ("highshelf", 9000, 0.7, -1.0))
    drums = compressor(drums, thr=-16, ratio=2.0, attack=0.01, release=0.12)
    drums = tame(drums, 12.0)
    # bass
    bass = eq(B, ("hp", 35, 0.7), ("lowshelf", 110, 0.7, 1.5), ("peak", 250, 1.0, -1.0), ("highshelf", 2500, 0.7, -3.0))
    bass = compressor(bass, thr=-20, ratio=3.0, attack=0.01, release=0.15)
    mid = (bass[:, 0] + bass[:, 1]) * 0.5
    bass = np.stack([mid, mid], axis=1)
    # keys
    plate = plate_ir(2.2, predelay=0.025, seed=3)
    keys = K["ep"] * undb(-1.0) + K["piano"] * undb(-3.0)
    keys = eq(keys, ("hp", 120, 0.7), ("peak", 300, 1.0, -2.0), ("highshelf", 8000, 0.7, -1.0))
    keys = tame(keys, 12.0)
    strings = K["strings"] * undb(-4.0) + K["pad"] * undb(-7.0)
    strings = eq(strings, ("hp", 150, 0.7), ("peak", 2500, 1.0, -2.0), ("highshelf", 7000, 0.7, -3.0))
    mallets = M["glock"] * undb(-9.0) + M["celesta"] * undb(-6.0) + M["organ"] * undb(-5.0)
    mallets = eq(mallets, ("hp", 200, 0.7), ("highshelf", 9000, 0.7, -2.0))
    # stage the band (relative active RMS), then the arrangement's section dynamics
    drums, _ = norm_to(drums, -20.0)
    bass, _ = norm_to(bass, -23.0)
    keys, _ = norm_to(keys, -26.0)
    strings, _ = norm_to(strings, -29.0)
    mallets, _ = norm_to(mallets, -28.0)
    wet = convolve(keys * undb(-14) + strings * undb(-10) + mallets * undb(-12), plate)
    sec_db = {"boot": 0.0, "intro": 0.0, "verse1": -2.0, "pre1": -1.0, "chorus1": 1.0, "post1": 0.0, "verse2": -2.0,
              "pre2": -1.0, "chorus2": 1.0, "post2": 0.0, "bridge": -0.5, "breakdown": 0.5, "chorus3": 1.5,
              "outro": -1.0, "tail": 0.0}
    sg = section_gain(S, DUR, sec_db)[:, None]
    groups = {"drums": drums * sg, "bass": bass * sg, "keys": keys * sg, "strings": strings * sg,
              "mallets": mallets * sg, "bedverb": wet * sg}

    # ---- vocals: channel strips, plate, pocket
    vtracks = {}
    for k in ("lead", "chant", "choir", "spoken", "chops"):
        if k in V:
            vtracks[k] = vocal_chain(V[k], k)
    vt = {"lead": 0.0, "chant": -1.0, "choir": -1.5, "spoken": 0.0, "chops": -7.0}
    for k in vtracks:
        vtracks[k], _ = norm_to(vtracks[k], -20.0 + vt[k])
    vplate = plate_ir(2.0, predelay=0.03, seed=7)
    sends = {"lead": -15.0, "chant": -19.0, "choir": -11.0, "spoken": -20.0, "chops": -12.0}
    vwet = convolve(sum(vtracks[k] * undb(sends[k]) for k in vtracks), vplate)
    vwet = eq(vwet, ("hp", 250, 0.7), ("highshelf", 6000, 0.7, -3.0))
    vdry = sum(vtracks.values())
    # the band makes a little room for every word (dynamic EQ keyed by the dry voices)
    for k in ("keys", "strings", "mallets"):
        groups[k] = pocket(groups[k], vdry, lo=800, hi=5000, depth=3.0)
    groups["drums"] = pocket(groups["drums"], vdry, lo=1500, hi=6000, depth=1.5)
    # a gentle presence dip in the band where the consonants live
    for k in ("drums", "keys", "strings", "mallets"):
        groups[k] = eq(groups[k], ("peak", 3300, 1.1, -2.5))
    bed = sum(groups.values())
    vox = vdry + vwet

    # ---- vocals over the bed: +3.5 dB in 1-5 kHz on sung frames, section by section
    g_glob = 0.0
    r, _ = band_ratio(vox, bed)
    g_glob = VOX_OVER_BED - r
    vox_g = vox * undb(g_glob)
    per = {}
    gdb = {}
    for s in S["sections"]:
        a, b = n_of(s["startBeat"] * spb), min(N, n_of((s["startBeat"] + s["beats"]) * spb))
        rr, nfr = band_ratio(vox_g[a:b], bed[a:b])
        if rr is None or nfr < 10:
            continue
        gdb[s["name"]] = float(np.clip(VOX_OVER_BED - rr, -6.0, 4.0))
    vg = section_gain(S, DUR, gdb, ramp=0.08)[:, None]
    vox = vox * undb(g_glob) * vg
    vdry = vdry * undb(g_glob) * vg
    for k in vtracks:
        vtracks[k] = vtracks[k] * undb(g_glob) * vg
    for s in S["sections"]:
        a, b = n_of(s["startBeat"] * spb), min(N, n_of((s["startBeat"] + s["beats"]) * spb))
        rr, nfr = band_ratio(vox[a:b], bed[a:b])
        if rr is not None and nfr >= 10:
            per[s["name"]] = round(rr, 2)
    log("vocals over bed (1-5 kHz, sung frames): global gain %+.1f dB, sections %s" % (g_glob, per))

    # ---- the silent pen: the band gone (8 ms fade) over the window, the keystroke alone in it
    sil = band.sil
    m = np.ones(N)
    for a, z in sil:
        ia, iz = n_of(a), n_of(z)
        f = n_of(0.008)
        m[ia - f:ia] = np.linspace(1, 0, f)
        m[ia:iz] = 0.0
        m[iz:iz + f] = np.linspace(0, 1, f)
    bed = bed * m[:, None]
    for k in groups:
        groups[k] = groups[k] * m[:, None]
    ks = dr["keystroke"]
    ks, _ = norm_to(ks, -44.0)
    bed = bed + ks
    groups["drums"] = groups["drums"] + ks

    # ---- master: bus glue -> true-peak limiter, input gain iterated to -14 LUFS
    mix = bed + vox
    mix = eq(mix, ("hp", 28, 0.7))
    _, gc = compressor(mix, thr=-14.0, ratio=1.5, attack=0.03, release=0.25, mode="rms", return_gain=True)

    def master(gin):
        y = mix * (gc * undb(gin))[:, None]
        y, gl = limiter(y, ceiling_db=CEILING)
        return y, gl
    gin = TARGET_LUFS - lufs(mix * gc[:, None])
    for _ in range(5):
        y, gl = master(gin)
        L = lufs(y)
        if abs(L - TARGET_LUFS) < 0.03:
            break
        gin += (TARGET_LUFS - L) * 1.1
    # end: the last 0.35 s fade to exact zero
    tail = np.ones(N)
    f = n_of(0.35)
    tail[N - f:] = np.linspace(1, 0, f) ** 2
    G = gc * undb(gin) * gl * tail
    y = mix * G[:, None]
    log("master: %.2f LUFS, %.2f dBTP, input gain %+.1f dB, limiter max %.2f dB" %
        (lufs(y), db(true_peak(y)), gin, -float(db(gl.min()))))

    os.makedirs(BUILD, exist_ok=True)
    os.makedirs(os.path.join(BUILD, "guide_stems"), exist_ok=True)
    assert len(y) == N
    sf.write(os.path.join(BUILD, "guide.wav"), y.astype(np.float32), SR, subtype="PCM_24")
    sf.write(os.path.join(BUILD, "guide_vocals.wav"), (vox * G[:, None]).astype(np.float32), SR, subtype="PCM_24")
    sf.write(os.path.join(BUILD, "guide_instrumental.wav"), (bed * G[:, None]).astype(np.float32), SR, subtype="PCM_24")
    for k, x in vtracks.items():
        sf.write(os.path.join(BUILD, "guide_stems", k + ".wav"), (x * G[:, None]).astype(np.float32), SR, subtype="PCM_24")
    for k, x in groups.items():
        sf.write(os.path.join(BUILD, "guide_stems", k + ".wav"), (x * G[:, None]).astype(np.float32), SR, subtype="PCM_24")
    for k, x in dr.items():
        sf.write(os.path.join(BUILD, "guide_stems", "dr_" + k + ".wav"), x.astype(np.float32), SR, subtype="PCM_24")
    log("wrote build/guide.wav, guide_vocals.wav, guide_instrumental.wav, guide_stems/")
    info = {"vox_over_bed_1_5k_db": per, "vox_global_gain_db": round(g_glob, 2),
            "vox_section_gain_db": {k: round(v, 2) for k, v in gdb.items()}, "master_input_gain_db": round(gin, 2),
            "limiter_max_db": round(-float(db(gl.min())), 2)}
    with open(os.path.join(BUILD, "guide-mix.json"), "w") as f:
        json.dump(info, f, indent=1)
    if not args.no_qa:
        import guide_qa
        guide_qa.run(S, EVENTS, DUR, whisper=not args.no_whisper, mix_info=info, log=log)


if __name__ == "__main__":
    main()
