#!/usr/bin/env python3
"""export_timing.py: reads music/score.json and writes data/data.js for the video.

Run:  python3 -I music/export_timing.py

data.js defines plain globals (no modules):
  LYRICS   [{text, id, section, voice, role?, start, end, words: [{w, start, end, syl?, silent?}]}]  seconds
  SECTIONS [{name, label, start, end}]
  BEATS    [seconds of every beat]        BARS [seconds of every bar start]
  HITS     {name: seconds}                ERAS [{name, start, note}]
  BPM, DUR (seconds), TITLE
Never hand-edit timings in the video: regenerate this file.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SCORE = os.path.join(HERE, "score.json")
OUT = os.path.join(os.path.dirname(HERE), "data", "data.js")


def main():
    with open(SCORE) as f:
        S = json.load(f)
    bpm = S["bpm"]
    spb = 60.0 / bpm

    def sec(beat):
        return round(beat * spb, 3)

    lyrics = []
    for L in S["lines"]:
        words = []
        for w in L["words"]:
            n0, n1 = w["notes"][0], w["notes"][-1]
            entry = {"w": w["w"], "start": sec(n0[1]), "end": sec(n1[1] + n1[2])}
            if "syl" in w:
                entry["syl"] = w["syl"]
            if w.get("silent"):
                entry["silent"] = True
            words.append(entry)
        item = {"text": L["text"], "id": L["id"], "section": L["section"], "voice": L["voice"],
                "start": words[0]["start"], "end": words[-1]["end"], "words": words}
        if "role" in L:
            item["role"] = L["role"]
        lyrics.append(item)
    lyrics.sort(key=lambda l: l["start"])

    sections = [{"name": s["name"], "label": s.get("label", s["name"]), "start": sec(s["startBeat"]),
                 "end": sec(s["startBeat"] + s["beats"])} for s in sorted(S["sections"], key=lambda s: s["startBeat"])]
    dur_beats = S["durationBeats"]
    beats = [sec(b) for b in range(dur_beats + 1)]
    bars = [sec(b) for b in range(0, dur_beats + 1, S["beatsPerBar"])]
    hits = {k: sec(v) for k, v in sorted(S["parts"]["hits"].items(), key=lambda kv: kv[1])}
    eras = [{"name": e["name"], "start": sec(e["startBeat"]), "note": e.get("note", "")} for e in S["parts"].get("eras", [])]
    dur = sec(dur_beats)

    def js(name, value):
        return "const %s = %s;\n" % (name, json.dumps(value, ensure_ascii=False, separators=(",", ":")))

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("// Generated by music/export_timing.py from music/score.json. Do not edit: regenerate.\n")
        f.write("// %s: %d bpm, %.1f s. Times in seconds.\n" % (S["title"], bpm, dur))
        f.write(js("TITLE", S["title"]))
        f.write(js("BPM", bpm))
        f.write(js("DUR", dur))
        f.write(js("SECTIONS", sections))
        f.write(js("HITS", hits))
        f.write(js("ERAS", eras))
        f.write(js("BEATS", beats))
        f.write(js("BARS", bars))
        f.write("const LYRICS = [\n")
        for l in lyrics:
            f.write("  %s,\n" % json.dumps(l, ensure_ascii=False, separators=(",", ":")))
        f.write("];\n")
    print("wrote %s: %d lines, %d sections, %d hits, DUR %.1f s" % (OUT, len(lyrics), len(sections), len(hits), dur))


if __name__ == "__main__":
    main()
