// The browse origin, served by the same Node process as the desk.
//
// Time Machine's web engine shows a proxied page in an iframe whose origin is
// not the desk's: the desk keeps the writer's projects in IndexedDB, and a
// page from the open web must never share an origin with that. This module
// answers every request whose Host is the browse host, and nothing else
// answers them: the desk's API routes and static files are not reachable
// here, and nothing here is reachable from the desk's host.
//
//   /__ais6/sw.js, /__ais6/shim.js ...  the engine's own files (apps/browse)
//   /__ais6/relay                        one request out to the web
//   /__ais6/relay-ws                     one WebSocket out to the web
//   anything else                        the bootstrap page, which installs
//                                        the service worker and reloads
//
// The relay's rules (who may use it, which headers and cookies cross) live in
// core.mjs, shared with the Pages Functions copy. What lives here is only how
// Node moves bytes: DNS-pinned sockets, streaming both ways, byte caps.

"use strict";

const fs = require("node:fs");
const http = require("node:http");
const https = require("node:https");
const path = require("node:path");
const crypto = require("node:crypto");
const zlib = require("node:zlib");

const core = require("./core.mjs");
const { resolveReaderTarget, isPrivateAddress } = require("../reader.js");
const { httpProxyAgentFor } = require("../lib/proxy.js");
const { localProxyRoute } = require("../lib/proxy-route.js");
const { isPublicDeployment } = require("../runtime-profile.js");
const { clientIp } = require("../security/public-session.js");

const browseRoot = path.resolve(__dirname, "..", "..", "..", "browse");
// Generated by `npm run browse:build-filters` from the pinned uBlock Origin
// Lite release; ignored by git, shipped with the runtime as part of apps/browse.
const generatedRoot = path.join(browseRoot, "filters");

const RELAY_TIMEOUT_MS = 85000;
const RELAY_REQUEST_BODY_MAX = 25 * 1024 * 1024;
const RELAY_RESPONSE_MAX = isPublicDeployment ? 40 * 1024 * 1024 : 1024 * 1024 * 1024;
const PUBLIC_REQUESTS_PER_MINUTE = 900;
const PUBLIC_BYTES_PER_DAY = 1024 * 1024 * 1024;
const PUBLIC_CONCURRENT = 16;

// --- Configuration ---------------------------------------------------------

/** @type {{ origin: string, host: string, secret: string, available: boolean, reason: string } | null} */
let cachedConfig = null;

/**
 * Where the browse origin lives. A Mac uses browse.localhost: browsers send
 * *.localhost to the loopback interface and treat it as a secure context, so
 * the service worker may register there, and it is a different origin from
 * both localhost and 127.0.0.1, where the desk may be open.
 *
 * @param {number} [port]
 */
function browseConfig(port = Number(process.env.PORT || 4173)) {
  if (cachedConfig) return cachedConfig;
  const configured = String(process.env.AI_SYSTEM6_BROWSE_ORIGIN || "").trim();
  let origin = configured || (isPublicDeployment ? "" : `http://browse.localhost:${port}`);
  let reason = "";
  try {
    const parsed = new URL(origin);
    if (parsed.pathname !== "/" || parsed.search || parsed.hash || parsed.username || parsed.password) {
      throw new Error("bad");
    }
    origin = parsed.origin;
  } catch {
    origin = "";
    reason = isPublicDeployment ? "browse_origin_not_configured" : "browse_origin_invalid";
  }
  let secret = String(process.env.AI_SYSTEM6_BROWSE_SECRET || "");
  if (secret.length < 24) {
    if (isPublicDeployment) {
      secret = "";
      reason ||= "browse_secret_not_configured";
    } else {
      // A Mac's relay lives as long as its server; tokens and sealed jars from
      // an earlier run are meant to stop opening when it restarts.
      secret = crypto.randomBytes(32).toString("base64url");
    }
  }
  cachedConfig = {
    origin,
    host: origin ? new URL(origin).host.toLowerCase() : "",
    secret,
    available: !!origin && !!secret,
    reason,
  };
  return cachedConfig;
}

/** @param {import("node:http").IncomingMessage} req */
function isBrowseHostRequest(req) {
  const config = browseConfig();
  if (!config.available) return false;
  return String(req.headers.host || "").toLowerCase() === config.host;
}

/** @param {import("node:http").IncomingMessage} req */
async function browseClientBinding(req) {
  if (!isPublicDeployment) return "";
  return core.browseClientDigest(clientIp(req), String(req.headers["user-agent"] || ""));
}

// --- Token route (desk host) ------------------------------------------------

/**
 * POST /api/browse/token. Runs behind the desk's own guard: Turnstile session
 * on the public site, the loopback origin check on a Mac.
 *
 * @param {import("node:http").IncomingMessage} req
 * @param {import("node:http").ServerResponse} res
 */
async function handleBrowseToken(req, res) {
  const config = browseConfig();
  res.setHeader("Cache-Control", "no-store");
  if (!config.available) {
    res.writeHead(503, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ error: "The web engine is not set up on this server.", code: config.reason }));
    return;
  }
  const body = await readSmallJson(req);
  const minted = await core.mintBrowseToken(config.secret, {
    sid: typeof body?.sid === "string" ? body.sid : undefined,
    client: await browseClientBinding(req),
  });
  res.writeHead(200, { "Content-Type": "application/json" });
  res.end(JSON.stringify({ ...minted, origin: config.origin }));
}

/** @param {import("node:http").IncomingMessage} req */
function readSmallJson(req) {
  return new Promise((resolve) => {
    let size = 0;
    /** @type {Buffer[]} */
    const chunks = [];
    req.on("data", (chunk) => {
      size += chunk.length;
      if (size > 4096) {
        req.destroy();
        resolve(null);
        return;
      }
      chunks.push(chunk);
    });
    req.on("end", () => {
      try {
        resolve(chunks.length ? JSON.parse(Buffer.concat(chunks).toString("utf8")) : {});
      } catch {
        resolve({});
      }
    });
    req.on("error", () => resolve(null));
  });
}

// --- Browse host ------------------------------------------------------------

const engineFiles = new Map([
  ["/__ais6/sw.js", { file: path.join(browseRoot, "sw.js"), type: "text/javascript; charset=utf-8" }],
  ["/__ais6/shim.js", { file: path.join(browseRoot, "shim.js"), type: "text/javascript; charset=utf-8" }],
  ["/__ais6/boot.js", { file: path.join(browseRoot, "boot.js"), type: "text/javascript; charset=utf-8" }],
  ["/__ais6/clear.js", { file: path.join(browseRoot, "clear.js"), type: "text/javascript; charset=utf-8" }],
  ["/__ais6/filter-match.js", { file: path.join(browseRoot, "filter-match.js"), type: "text/javascript; charset=utf-8" }],
  ["/__ais6/filters/network.json", { file: path.join(generatedRoot, "network.json"), type: "application/json" }],
  ["/__ais6/filters/cosmetic.json", { file: path.join(generatedRoot, "cosmetic.json"), type: "application/json" }],
]);

/**
 * The origins allowed to frame the browse origin: the desk's own. Anything
 * else framing it could drive a writer's sealed logins.
 */
function deskFrameAncestors() {
  if (isPublicDeployment) {
    return String(process.env.AI_SYSTEM6_PUBLIC_ORIGIN || "https://system6.aaronlau.me");
  }
  const port = Number(process.env.PORT || 4173);
  return `http://127.0.0.1:${port} http://localhost:${port}`;
}

/**
 * @param {import("node:http").ServerResponse} res
 * @param {Record<string, string>} [extra]
 */
function browseHostHeaders(res, extra = {}) {
  res.setHeader("X-Content-Type-Options", "nosniff");
  res.setHeader("Content-Security-Policy", `frame-ancestors ${deskFrameAncestors()}`);
  res.setHeader("Referrer-Policy", "same-origin");
  for (const [name, value] of Object.entries(extra)) res.setHeader(name, value);
}

/**
 * @param {import("node:http").IncomingMessage} req
 * @param {import("node:http").ServerResponse} res
 */
async function handleBrowseHost(req, res) {
  // The desk's own security headers were applied before dispatch; none of
  // them describe this origin.
  for (const name of res.getHeaderNames()) {
    if (name !== "x-request-id") res.removeHeader(name);
  }
  let url;
  try {
    url = new URL(req.url || "/", `http://${req.headers.host}`);
  } catch {
    res.writeHead(400).end();
    return;
  }
  if (url.pathname === "/__ais6/relay") {
    await handleRelay(req, res);
    return;
  }
  // The worker's own settings: who may frame the pages it serves. It cannot
  // take this from a page (a page can say anything), so it asks the server.
  if (url.pathname === "/__ais6/config.json" && req.method === "GET") {
    browseHostHeaders(res, { "Content-Type": "application/json", "Cache-Control": "no-store" });
    res.writeHead(200);
    res.end(JSON.stringify({ frameAncestors: deskFrameAncestors() }));
    return;
  }
  if (url.pathname === "/__ais6/clear.html" && req.method === "GET") {
    browseHostHeaders(res, { "Content-Type": "text/html; charset=utf-8", "Cache-Control": "no-store" });
    res.writeHead(200);
    res.end("<!doctype html><meta charset=\"utf-8\"><title></title><script src=\"/__ais6/clear.js\"></script>");
    return;
  }
  const engineFile = engineFiles.get(url.pathname);
  if (engineFile && (req.method === "GET" || req.method === "HEAD")) {
    serveEngineFile(req, res, url.pathname, engineFile);
    return;
  }
  // Every other path is the bootstrap: a navigation that arrived before the
  // service worker was installed (the first visit, or after the browser
  // evicted it). It installs the worker and loads the same address again.
  const accept = String(req.headers.accept || "");
  if ((req.method === "GET" || req.method === "HEAD") && (accept.includes("text/html") || url.pathname === "/__ais6/go")) {
    browseHostHeaders(res, {
      "Content-Type": "text/html; charset=utf-8",
      "Cache-Control": "no-store",
    });
    res.writeHead(200);
    res.end(req.method === "HEAD" ? undefined : bootstrapPage());
    return;
  }
  browseHostHeaders(res, { "Content-Type": "text/plain; charset=utf-8", "Cache-Control": "no-store" });
  res.writeHead(404);
  res.end("Not found");
}

function bootstrapPage() {
  return [
    "<!doctype html>",
    "<html><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">",
    "<title></title>",
    "<style>html,body{margin:0;height:100%;font:13px -apple-system,system-ui,sans-serif;color:#555;background:#fff}",
    "p{position:absolute;inset:auto 0 50% 0;text-align:center}</style>",
    "<script src=\"/__ais6/boot.js\"></script></head>",
    "<body><p id=\"ais6-boot\"></p></body></html>",
  ].join("");
}

/**
 * @param {import("node:http").IncomingMessage} req
 * @param {import("node:http").ServerResponse} res
 * @param {string} pathname
 * @param {{ file: string, type: string }} entry
 */
function serveEngineFile(req, res, pathname, entry) {
  readEngineFile(entry.file, (error, cached) => {
    if (error || !cached) {
      browseHostHeaders(res, { "Content-Type": "text/plain; charset=utf-8", "Cache-Control": "no-store" });
      res.writeHead(404);
      res.end("Not found");
      return;
    }
    const headers = {
      "Content-Type": entry.type,
      // The engine must update the moment the app does; a stale worker would
      // keep proxying with the previous release's rules. The ETag makes the
      // revalidation that "no-cache" asks for a 304 rather than a download:
      // the filter lists are megabytes, fetched each time the worker starts.
      "Cache-Control": "no-cache",
      ETag: cached.etag,
      Vary: "Accept-Encoding",
      ...(pathname === "/__ais6/sw.js" ? { "Service-Worker-Allowed": "/" } : {}),
    };
    if (String(req.headers["if-none-match"] || "") === cached.etag) {
      browseHostHeaders(res, headers);
      res.writeHead(304);
      res.end();
      return;
    }
    const gzip = /\bgzip\b/.test(String(req.headers["accept-encoding"] || "")) && cached.gzip;
    browseHostHeaders(res, gzip ? { ...headers, "Content-Encoding": "gzip" } : headers);
    res.writeHead(200);
    res.end(req.method === "HEAD" ? undefined : (gzip ? cached.gzip : cached.data));
  });
}

/** @type {Map<string, { mtimeMs: number, data: Buffer, gzip: Buffer | null, etag: string }>} */
const engineFileCache = new Map();

/**
 * @param {string} file
 * @param {(error: Error | null, cached?: { data: Buffer, gzip: Buffer | null, etag: string }) => void} callback
 */
function readEngineFile(file, callback) {
  fs.stat(file, (statError, stats) => {
    if (statError) return callback(statError);
    const cached = engineFileCache.get(file);
    if (cached && cached.mtimeMs === stats.mtimeMs) return callback(null, cached);
    fs.readFile(file, (readError, data) => {
      if (readError) return callback(readError);
      const entry = {
        mtimeMs: stats.mtimeMs,
        data,
        gzip: data.length > 1024 ? zlib.gzipSync(data, { level: 6 }) : null,
        etag: `"${crypto.createHash("sha1").update(data).digest("base64url")}"`,
      };
      engineFileCache.set(file, entry);
      callback(null, entry);
    });
  });
}

// --- Public limits ------------------------------------------------------------

/** @type {Map<string, { minute: number, minuteCount: number, day: number, dayBytes: number, active: number }>} */
const usage = new Map();

/** @param {string} sid */
function usageFor(sid) {
  const now = Date.now();
  const minute = Math.floor(now / 60000);
  const day = Math.floor(now / 86400000);
  let entry = usage.get(sid);
  if (!entry) {
    entry = { minute, minuteCount: 0, day, dayBytes: 0, active: 0 };
    usage.set(sid, entry);
    if (usage.size > 5000) {
      for (const [key, value] of usage) {
        if (value.active === 0 && value.day !== day) usage.delete(key);
        if (usage.size <= 4000) break;
      }
    }
  }
  if (entry.minute !== minute) {
    entry.minute = minute;
    entry.minuteCount = 0;
  }
  if (entry.day !== day) {
    entry.day = day;
    entry.dayBytes = 0;
  }
  return entry;
}

// --- Relay --------------------------------------------------------------------

/**
 * @param {import("node:http").ServerResponse} res
 * @param {number} status
 * @param {string} code
 * @param {string} message
 */
function relayFailure(res, status, code, message) {
  if (res.headersSent) {
    res.destroy();
    return;
  }
  browseHostHeaders(res, {
    "Content-Type": "application/json",
    "Cache-Control": "no-store",
    "X-AIS6-Error": code,
  });
  res.writeHead(status);
  res.end(JSON.stringify({ error: message, code }));
}

/**
 * @param {import("node:http").IncomingMessage} req
 * @param {number} limit
 * @returns {Promise<Buffer>}
 */
function readRequestBody(req, limit) {
  return new Promise((resolve, reject) => {
    /** @type {Buffer[]} */
    const chunks = [];
    let size = 0;
    req.on("data", (chunk) => {
      size += chunk.length;
      if (size > limit) {
        reject(core.browseError("The page tried to send more than this relay carries.", "browse_request_too_large", 413));
        req.destroy();
        return;
      }
      chunks.push(chunk);
    });
    req.on("end", () => resolve(Buffer.concat(chunks)));
    req.on("error", reject);
  });
}

/**
 * How one request leaves this machine. The public server connects directly
 * to the address that passed the private-network check (pinned, so DNS
 * cannot change between the check and the connection). A Mac whose owner
 * routes the web through a proxy (common where many sites are blocked)
 * goes through that proxy, as the writer's own browser does; the name is
 * still checked here first, and an answer naming a private network is
 * refused.
 *
 * @param {URL} target
 */
async function upstreamRoute(target) {
  const proxy = await localProxyRoute(target.href, isPrivateAddress).catch((error) => {
    throw core.browseError(error.message, "browse_private_address", 403);
  });
  if (proxy) return { agent: httpProxyAgentFor(proxy) };
  const resolved = await resolveReaderTarget(target.href);
  return {
    lookup: (_hostname, options, callback) => {
      if (options?.all) callback(null, [{ address: resolved.address, family: resolved.family }]);
      else callback(null, resolved.address, resolved.family);
    },
  };
}

/**
 * One hop: a single upstream request on a socket pinned to the address that
 * passed the private-network check, so a DNS answer cannot change between the
 * check and the connection.
 *
 * @param {URL} target
 * @param {string} method
 * @param {Record<string, string>} headers
 * @param {Buffer | null} body
 * @param {AbortSignal} signal
 * @returns {Promise<import("node:http").IncomingMessage>}
 */
async function upstreamRequest(target, method, headers, body, signal) {
  const route = await upstreamRoute(target);
  const transport = target.protocol === "https:" ? https : http;
  return new Promise((resolve, reject) => {
    const request = transport.request(target, {
      method,
      headers: body && body.length ? { ...headers, "content-length": String(body.length) } : headers,
      ...route,
      servername: target.hostname,
      signal,
    }, resolve);
    request.on("error", reject);
    request.setTimeout(RELAY_TIMEOUT_MS, () => request.destroy(core.browseError("The site took too long to answer.", "browse_timeout", 504)));
    request.end(body && body.length ? body : undefined);
  });
}

/**
 * @param {import("node:http").IncomingMessage} req
 * @param {import("node:http").ServerResponse} res
 */
async function handleRelay(req, res) {
  const config = browseConfig();
  const envelope = core.readRelayEnvelope((name) => {
    const value = req.headers[name];
    return Array.isArray(value) ? value[0] : value;
  });
  const verified = await core.verifyBrowseToken(config.secret, envelope.token, { client: await browseClientBinding(req) });
  if (!verified.ok) {
    relayFailure(res, 401, `browse_token_${"reason" in verified ? verified.reason : "invalid"}`, "This page needs to be opened again from Time Machine.");
    return;
  }
  const meter = usageFor(verified.sid);
  if (isPublicDeployment) {
    meter.minuteCount += 1;
    if (meter.minuteCount > PUBLIC_REQUESTS_PER_MINUTE || meter.active >= PUBLIC_CONCURRENT) {
      relayFailure(res, 429, "browse_rate_limited", "Too many requests at once. Wait a moment.");
      return;
    }
    if (meter.dayBytes > PUBLIC_BYTES_PER_DAY) {
      relayFailure(res, 429, "browse_daily_limit", "Today's browsing allowance on this server is used up.");
      return;
    }
  }

  const controller = new AbortController();
  const abort = () => controller.abort();
  // The response's close, not the request's: a request emits close as soon
  // as its body has been read, which for a GET is immediately.
  res.on("close", () => {
    if (!res.writableFinished) abort();
  });
  meter.active += 1;
  try {
    let target = core.browseTargetUrl(envelope.url);
    let method = String(req.method || "GET").toUpperCase();
    let body = method === "GET" || method === "HEAD" ? null : await readRequestBody(req, RELAY_REQUEST_BODY_MAX);
    const site = core.browseSiteKey(target.hostname);
    let jar = await core.openJar(config.secret, verified.sid, site, envelope.jar);
    const jarBefore = JSON.stringify(jar);
    for (const assignment of envelope.documentCookies) {
      jar = core.applyDocumentCookie(jar, assignment, target);
    }
    let referrer = envelope.referrer;
    let upstream;
    for (let hop = 0; ; hop += 1) {
      /** @type {Record<string, string>} */
      const headers = {
        ...envelope.headers,
        "user-agent": core.relayUserAgent(envelope.userAgent),
        "accept-encoding": "gzip, deflate, br",
        ...core.relayProvenanceHeaders({ referrer, origin: envelope.origin }, target, method),
      };
      if (!headers.accept) headers.accept = "*/*";
      const cookie = core.cookiesFor(jar, target);
      if (cookie) headers.cookie = cookie;
      upstream = await upstreamRequest(target, method, headers, body, controller.signal);
      const setCookies = upstream.headers["set-cookie"] || [];
      for (const value of setCookies) {
        const parsed = core.parseSetCookie(value, target);
        // Cookies for another site are dropped rather than filed under the
        // site that sent them; they would never be sent back anyway.
        if (parsed && core.browseSiteKey(parsed.domain) === site) jar = core.storeCookie(jar, parsed);
      }
      const status = upstream.statusCode || 0;
      const location = upstream.headers.location;
      if (!envelope.follow || ![301, 302, 303, 307, 308].includes(status) || !location) break;
      if (hop >= core.BROWSE_MAX_REDIRECTS) {
        upstream.resume();
        throw core.browseError("The site redirected too many times.", "browse_redirect_loop", 508);
      }
      upstream.resume();
      const next = core.browseTargetUrl(new URL(String(location), target).href);
      // A redirect to another site leaves this site's jar behind: the next
      // site's cookies are in a different sealed jar, which this request did
      // not carry. The hop goes back to the service worker, which asks again
      // with the right jar (and, for a page, moves the frame to the new site).
      if (core.browseSiteKey(next.hostname) !== site) {
        await sendRedirectHop(res, next, status, jar, jarBefore, config, verified.sid, site);
        return;
      }
      referrer = target.href;
      target = next;
      if (status === 303 || ((status === 301 || status === 302) && method !== "GET" && method !== "HEAD")) {
        method = "GET";
        body = null;
      }
    }

    const responseHeaders = core.browseResponseHeaders(Object.entries(upstream.headers));
    /** @type {Record<string, string>} */
    const relayHeaders = {
      "Cache-Control": "no-store",
      "X-AIS6-Status": String(upstream.statusCode || 502),
      "X-AIS6-Status-Text": encodeURIComponent(upstream.statusMessage || ""),
      "X-AIS6-Headers": JSON.stringify(responseHeaders),
      "X-AIS6-Final-Url": encodeURIComponent(target.href),
    };
    if (JSON.stringify(jar) !== jarBefore) {
      relayHeaders["X-AIS6-Jar"] = await core.sealJar(config.secret, verified.sid, site, jar);
      relayHeaders["X-AIS6-Jar-Site"] = site;
    }
    if (envelope.wantDocumentCookies) {
      relayHeaders["X-AIS6-Doc-Cookies"] = encodeURIComponent(core.cookiesFor(jar, target, { includeHttpOnly: false }));
    }
    const encoding = String(upstream.headers["content-encoding"] || "").toLowerCase();
    // The browser undoes the site's compression for the service worker, so
    // the bytes are passed through as they came and never inflated here.
    if (["gzip", "deflate", "br"].includes(encoding)) relayHeaders["Content-Encoding"] = encoding;
    if (upstream.headers["content-type"]) relayHeaders["Content-Type"] = String(upstream.headers["content-type"]);
    browseHostHeaders(res, relayHeaders);
    res.writeHead(200);
    if (method === "HEAD") {
      upstream.resume();
      res.end();
      return;
    }
    let sent = 0;
    upstream.on("data", (chunk) => {
      sent += chunk.length;
      meter.dayBytes += chunk.length;
      if (sent > RELAY_RESPONSE_MAX) {
        upstream.destroy();
        res.destroy();
        return;
      }
      if (!res.write(chunk)) {
        upstream.pause();
        res.once("drain", () => upstream.resume());
      }
    });
    upstream.on("end", () => res.end());
    upstream.on("error", () => res.destroy());
  } catch (error) {
    const err = /** @type {any} */ (error);
    if (err?.name === "AbortError") {
      res.destroy();
      return;
    }
    relayFailure(
      res,
      Number(err?.statusCode) || 502,
      String(err?.code || "browse_upstream_failed"),
      /^(browse|reader)_/.test(String(err?.code || "")) ? String(err.message) : "The site could not be reached."
    );
  } finally {
    meter.active = Math.max(0, meter.active - 1);
  }
}

/**
 * @param {import("node:http").ServerResponse} res
 * @param {URL} next
 * @param {number} status
 * @param {any[]} jar
 * @param {string} jarBefore
 * @param {{ secret: string }} config
 * @param {string} sid
 * @param {string} site
 */
async function sendRedirectHop(res, next, status, jar, jarBefore, config, sid, site) {
  /** @type {Record<string, string>} */
  const headers = {
    "Cache-Control": "no-store",
    "Content-Type": "text/plain; charset=utf-8",
    "X-AIS6-Status": String(status),
    "X-AIS6-Status-Text": "",
    "X-AIS6-Headers": JSON.stringify({ location: next.href }),
    "X-AIS6-Final-Url": encodeURIComponent(next.href),
    "X-AIS6-Redirect": encodeURIComponent(next.href),
  };
  // The site that redirected may have set cookies on the way out (a login
  // completing, for instance); those are kept even though the page leaves.
  if (JSON.stringify(jar) !== jarBefore) {
    headers["X-AIS6-Jar"] = await core.sealJar(config.secret, sid, site, jar);
    headers["X-AIS6-Jar-Site"] = site;
  }
  browseHostHeaders(res, headers);
  res.writeHead(200);
  res.end();
}

// --- WebSocket relay ------------------------------------------------------------

/** @type {any} */
let wsModule = null;

/**
 * GET /__ais6/relay-ws?u=&k=&j=&p= upgraded on the browse host.
 *
 * @param {import("node:http").IncomingMessage} req
 * @param {import("node:stream").Duplex} socket
 * @param {Buffer} head
 */
async function handleBrowseUpgrade(req, socket, head) {
  const reject = (status) => {
    socket.end(`HTTP/1.1 ${status} Refused\r\nConnection: close\r\nContent-Length: 0\r\n\r\n`);
  };
  try {
    const config = browseConfig();
    const url = new URL(req.url || "/", `http://${req.headers.host}`);
    if (url.pathname !== "/__ais6/relay-ws") return reject(404);
    const origin = String(req.headers.origin || "");
    if (origin !== config.origin) return reject(403);
    const verified = await core.verifyBrowseToken(config.secret, url.searchParams.get("k") || "", { client: await browseClientBinding(req) });
    if (!verified.ok) return reject(401);
    const target = core.browseTargetUrl(url.searchParams.get("u") || "", { websocket: true });
    const route = await upstreamRoute(new URL(target.href.replace(/^ws/, "http")));
    const site = core.browseSiteKey(target.hostname);
    const jar = await core.openJar(config.secret, verified.sid, site, url.searchParams.get("j") || "");
    const pageOrigin = url.searchParams.get("o") || "";
    const protocols = String(url.searchParams.get("p") || "").split(",").map((value) => value.trim()).filter(Boolean).slice(0, 8);
    wsModule ||= require("ws");
    const upstream = new wsModule.WebSocket(target.href, protocols, {
      headers: {
        "user-agent": core.relayUserAgent(String(req.headers["user-agent"] || "")),
        ...(core.cookiesFor(jar, new URL(target.href.replace(/^ws/, "http"))) ? { cookie: core.cookiesFor(jar, new URL(target.href.replace(/^ws/, "http"))) } : {}),
        ...(pageOrigin ? { origin: new URL(pageOrigin).origin } : {}),
      },
      ...route,
      servername: target.hostname,
      maxPayload: 16 * 1024 * 1024,
      handshakeTimeout: 20000,
    });
    upstream.once("open", () => {
      const server = new wsModule.WebSocketServer({ noServer: true, maxPayload: 16 * 1024 * 1024 });
      server.handleUpgrade(req, socket, head, (client) => {
        const meter = usageFor(verified.sid);
        client.on("message", (data, isBinary) => {
          if (upstream.readyState === 1) upstream.send(data, { binary: isBinary });
        });
        upstream.on("message", (data, isBinary) => {
          meter.dayBytes += Buffer.isBuffer(data) ? data.length : 0;
          if (isPublicDeployment && meter.dayBytes > PUBLIC_BYTES_PER_DAY) {
            client.close(1008, "daily limit");
            upstream.close();
            return;
          }
          if (client.readyState === 1) client.send(data, { binary: isBinary });
        });
        const closeBoth = (code, reason) => {
          const safeCode = typeof code === "number" && code >= 1000 && code < 5000 && code !== 1005 && code !== 1006 ? code : 1000;
          if (client.readyState <= 1) client.close(safeCode, String(reason || "").slice(0, 120));
          if (upstream.readyState <= 1) upstream.close(safeCode, String(reason || "").slice(0, 120));
        };
        client.on("close", closeBoth);
        upstream.on("close", closeBoth);
        client.on("error", () => closeBoth(1011, ""));
        upstream.on("error", () => closeBoth(1011, ""));
      });
    });
    upstream.once("unexpected-response", () => reject(502));
    upstream.once("error", () => {
      if (!socket.destroyed) reject(502);
    });
  } catch {
    reject(400);
  }
}

module.exports = {
  browseConfig,
  isBrowseHostRequest,
  handleBrowseHost,
  handleBrowseToken,
  handleBrowseUpgrade,
  // Exposed for the contract tests.
  bootstrapPage,
  deskFrameAncestors,
  resetBrowseConfigForTests: () => {
    cachedConfig = null;
  },
};
