/**
 * Single source of release identity for AI System 6.
 *
 * Every surface that reports or caches the version, build, commit, or
 * generated-at timestamp reads from the artifacts this module produces at
 * build time:
 *
 *   - app/generated/build-info.js   browser global loaded by index.html
 *   - app/generated/build-info.json server (/api/version) + native shell
 *   - index.html ?v= cache-busters  stamped in place, never hand-edited
 *
 * The generated JS file uses a JSON body so it stays parseable by the
 * consistency gate; do not reformat it by hand.
 */

import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");

/** Assets in index.html whose ?v= query must carry the current build stamp. */
export const stampedIndexAssets = [
  "styles.bundle.css",
  "app.bundle.js",
  "app/generated/build-info.js",
];

export const generatedJsPath = "app/generated/build-info.js";
export const generatedJsonPath = "app/generated/build-info.json";

function readJsonSafe(absPath) {
  try {
    return JSON.parse(readFileSync(absPath, "utf8"));
  } catch {
    return {};
  }
}

function readGitShortHead(root) {
  if (!existsSync(join(root, ".git"))) return "";
  try {
    return execFileSync("git", ["rev-parse", "--short", "HEAD"], {
      cwd: root,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    return "";
  }
}

/**
 * Resolve the release identity from package.json + build-info.json + git.
 * Missing or malformed inputs degrade to explicit dev markers, never to a
 * fake release number.
 */
export function resolveBuildInfo({ root = repoRoot } = {}) {
  const pkg = readJsonSafe(join(root, "package.json"));
  const buildInfo = readJsonSafe(join(root, "build-info.json"));
  return {
    version:
      typeof pkg.version === "string" && pkg.version
        ? pkg.version
        : "0.0.0-dev",
    build:
      typeof buildInfo.build === "string" && buildInfo.build
        ? buildInfo.build
        : "dev",
    commit: readGitShortHead(root),
    generatedAt: new Date().toISOString(),
  };
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Rewrite the ?v= cache-busters of the stamped assets in index.html. The
 * file keeps its generated stamp in the tree so a release checkout serves
 * cache-busted bundles without extra infrastructure.
 */
export function stampIndexHtml({ root = repoRoot, build }) {
  const indexPath = join(root, "index.html");
  if (!existsSync(indexPath)) return null;
  const source = readFileSync(indexPath, "utf8");
  let output = source;
  for (const asset of stampedIndexAssets) {
    const pattern = new RegExp(
      `((?:href|src)="${escapeRegExp(asset)})\\?v=[^"]*"`,
      "g"
    );
    output = output.replace(pattern, `$1?v=${encodeURIComponent(build)}"`);
  }
  if (output !== source) writeFileSync(indexPath, output, "utf8");
  return output;
}

/**
 * Write the browser JS + server JSON artifacts, then stamp index.html.
 * Returns the resolved identity. Runs before bundle assembly so every build
 * path (npm run build:app, verify:release, deploy) is self-consistent.
 */
export function generateBuildInfo({ root = repoRoot } = {}) {
  const info = resolveBuildInfo({ root });
  const jsonBody = JSON.stringify(info, null, 2);
  writeFileSync(
    join(root, generatedJsPath),
    [
      `// Generated by scripts/lib/build-info.mjs. Do not edit by hand.`,
      `// Single source of version/build/commit for browser, server, shell and`,
      `// index.html cache-busters.`,
      `window.AISystem6BuildInfo = Object.freeze(${jsonBody});`,
      ``,
    ].join("\n"),
    "utf8"
  );
  writeFileSync(join(root, generatedJsonPath), `${jsonBody}\n`, "utf8");
  stampIndexHtml({ root, build: info.build });
  return info;
}
